model: gpt-3.5-turbo # can be gpt-3.5-turbo or gpt-4, alpaca or vicuna
dataset: sentiment # can be hate-speech, sentiment, ten-dim, analyse-tal
sampling: balanced # can be proportional or balanced

debug_k: False