wandb_version: 1

ckpt:
  desc: null
  value: intfloat/e5-base
batch_size:
  desc: null
  value: 2
lr:
  desc: null
  value: 2.0e-05
num_epochs:
  desc: null
  value: 3
weight_decay:
  desc: null
  value: 0
train_size:
  desc: null
  value: 232
use_augmented_data:
  desc: null
  value: false
approach:
  desc: null
  value: simple
augmentation_model:
  desc: null
  value: gpt-3.5-turbo
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.28.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1686695319.628202
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 50
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 50
      - 51
      - 53
      - 55
      - 71
      3:
      - 13
      - 16
      - 23
      4: 3.10.10
      5: 0.15.2
      6: 4.28.1
      8:
      - 2
      - 5
